version: "3"
services:
    node:
        image: node:12-alpine
        working_dir: /app
        volumes:
            - .:/app
        tty: true
        environment:
            MONGO_URL: 'mongodb://root:example@mongo:27017/testing?authSource=admin'
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        expose:
            - 27017