name: CI

on: [ push, pull_request ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodejs: [ 14, 16, 18, 19, 20 ]
        name: Node ${{ matrix.node }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup node
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node }}
                    cache: 'npm'

            -   name: Install
                run: npm install

            -   name: Start MongoDB
                uses: supercharge/mongodb-github-action@1.7.0
                with:
                    mongodb-version: '5'
                    mongodb-username: 'root'
                    mongodb-password: 'example'
                    mongodb-db: 'testing'

            -   name: Test
                run: npm test
                env:
                    MONGO_URL: 'mongodb://root:example@localhost:27017/testing?authSource=admin'